code --install-extension absszero.vscode-laravel-goto
code --install-extension abusaidm.html-snippets
code --install-extension alefragnani.bookmarks
code --install-extension alexcvzz.vscode-sqlite
code --install-extension amiralizadeh9480.laravel-extra-intellisense
code --install-extension aswinkumar863.smarty-template-support
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension cefour.pretty-edit
code --install-extension christian-kohler.path-intellisense
code --install-extension cymonk.sql-formatter
code --install-extension donjayamanne.githistory
code --install-extension donjayamanne.python-environment-manager
code --install-extension donjayamanne.python-extension-pack
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension emilast.logfilehighlighter
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.docker-explorer
code --install-extension formulahendry.docker-extension-pack
code --install-extension formulahendry.vscode-mysql
code --install-extension golang.go
code --install-extension ibm.output-colorizer
code --install-extension ikappas.phpcs
code --install-extension iliazeus.vscode-ansi
code --install-extension jakebathman.mysql-syntax
code --install-extension johnheikens.intelliskript
code --install-extension johnheikens.skript
code --install-extension junstyle.php-cs-fixer
code --install-extension kelvin.vscode-sshfs
code --install-extension kevinrose.vsc-python-indent
code --install-extension mikeburgh.xml-format
code --install-extension mohamedbenhida.laravel-intellisense
code --install-extension mosapride.zenkaku
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-ceintl.vscode-language-pack-ja
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension mtxr.sqltools
code --install-extension mtxr.sqltools-driver-mysql
code --install-extension nemesv.copy-file-name
code --install-extension oderwat.indent-rainbow
code --install-extension onecentlin.laravel-blade
code --install-extension patricklee.vsnotes
code --install-extension qwtel.sqlite-viewer
code --install-extension redhat.java
code --install-extension redhat.vscode-xml
code --install-extension rifi2k.format-html-in-php
code --install-extension rust-lang.rust-analyzer
code --install-extension tabnine.tabnine-vscode
code --install-extension tomoki1207.pdf
code --install-extension tyriar.sort-lines
code --install-extension vadimcn.vscode-lldb
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension xdebug.php-debug
code --install-extension yzhang.markdown-all-in-one
code --install-extension zz5840.minecraft-lang-colorizer
