code --install-extension absszero.vscode-laravel-goto
code --install-extension abusaidm.html-snippets
code --install-extension alefragnani.Bookmarks
code --install-extension amiralizadeh9480.laravel-extra-intellisense
code --install-extension austin.vscode-twitter
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension cefour.pretty-edit
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension cweijan.vscode-autohotkey-plus
code --install-extension cymonk.sql-formatter
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension eiminsasete.apacheconf-snippets
code --install-extension emilast.LogFileHighlighter
code --install-extension esbenp.prettier-vscode
code --install-extension felixfbecker.php-debug
code --install-extension felixfbecker.php-intellisense
code --install-extension felixfbecker.php-pack
code --install-extension formulahendry.code-runner
code --install-extension formulahendry.vscode-mysql
code --install-extension GrapeCity.gc-excelviewer
code --install-extension IBM.output-colorizer
code --install-extension ikappas.phpcs
code --install-extension jakebathman.mysql-syntax
code --install-extension jebbs.plantuml
code --install-extension junstyle.php-cs-fixer
code --install-extension Kelvin.vscode-sshfs
code --install-extension mikeburgh.xml-format
code --install-extension mohamedbenhida.laravel-intellisense
code --install-extension mosapride.zenkaku
code --install-extension mrmlnc.vscode-apache
code --install-extension MS-CEINTL.vscode-language-pack-ja
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.powershell
code --install-extension mtxr.sqltools
code --install-extension nemesv.copy-file-name
code --install-extension onecentlin.laravel-blade
code --install-extension patricklee.vsnotes
code --install-extension pizzacat83.codic
code --install-extension qinjia.view-in-browser
code --install-extension redhat.java
code --install-extension redhat.vscode-xml
code --install-extension rifi2k.format-html-in-php
code --install-extension slevesque.vscode-autohotkey
code --install-extension TabNine.tabnine-vscode
code --install-extension tomoki1207.pdf
code --install-extension Tyriar.sort-lines
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-maven
code --install-extension yzane.markdown-pdf
code --install-extension yzhang.markdown-all-in-one
