code --install-extension absszero.vscode-laravel-goto
code --install-extension amiralizadeh9480.laravel-extra-intellisense
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension eiminsasete.apacheconf-snippets
code --install-extension esbenp.prettier-vscode
code --install-extension felixfbecker.php-debug
code --install-extension felixfbecker.php-pack
code --install-extension formulahendry.vscode-mysql
code --install-extension jakebathman.mysql-syntax
code --install-extension mikeburgh.xml-format
code --install-extension mohamedbenhida.laravel-intellisense
code --install-extension mrmlnc.vscode-apache
code --install-extension onecentlin.laravel-blade
code --install-extension redhat.vscode-xml
