code --install-extension alefragnani.Bookmarks
code --install-extension cefour.pretty-edit
code --install-extension christian-kohler.path-intellisense
code --install-extension donjayamanne.githistory
code --install-extension emilast.LogFileHighlighter
code --install-extension emilast.logfilehighlighter
code --install-extension formulahendry.docker-explorer
code --install-extension formulahendry.docker-extension-pack
code --install-extension ibm.output-colorizer
code --install-extension iliazeus.vscode-ansi
code --install-extension Kelvin.vscode-sshfs
code --install-extension mikeburgh.xml-format
code --install-extension mosapride.zenkaku
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-ja
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension nemesv.copy-file-name
code --install-extension oderwat.indent-rainbow
code --install-extension patricklee.vsnotes
code --install-extension redhat.vscode-xml
code --install-extension TabNine.tabnine-vscode
code --install-extension tomoki1207.pdf
code --install-extension Tyriar.sort-lines
code --install-extension yzhang.markdown-all-in-one
