code --install-extension absszero.vscode-laravel-goto
code --install-extension alefragnani.Bookmarks
code --install-extension amiralizadeh9480.laravel-extra-intellisense
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension cefour.pretty-edit
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension donjayamanne.githistory
code --install-extension eiminsasete.apacheconf-snippets
code --install-extension emilast.LogFileHighlighter
code --install-extension esbenp.prettier-vscode
code --install-extension felixfbecker.php-debug
code --install-extension felixfbecker.php-pack
code --install-extension formulahendry.vscode-mysql
code --install-extension IBM.output-colorizer
code --install-extension jakebathman.mysql-syntax
code --install-extension Kelvin.vscode-sshfs
code --install-extension mohamedbenhida.laravel-intellisense
code --install-extension mosapride.zenkaku
code --install-extension mrmlnc.vscode-apache
code --install-extension MS-CEINTL.vscode-language-pack-ja
code --install-extension nemesv.copy-file-name
code --install-extension onecentlin.laravel-blade
code --install-extension patricklee.vsnotes
code --install-extension TabNine.tabnine-vscode
code --install-extension Tyriar.sort-lines
code --install-extension yzhang.markdown-all-in-one
